// Shows how UI elements are dynamically generated by domain modules.
// This keeps UI composition decoupled from page-level logic.

using System;

public class JournalRenderer
{
    private readonly ModuleManager _moduleManager;

    public JournalRenderer(ModuleManager moduleManager)
    {
        _moduleManager = moduleManager;
    }

    public object? BuildJournalElement<T>(DateTime date) where T : IJnlModule, new()
    {
        var module = _moduleManager.GetOrCreateModule<T>();

        if (!module.HasDataForDate(date))
            return null;

        return module.GetJournalElement(date);
    }
}